### ISSUE TITLE
Créer un script qui transforme fichier .WAV en .CSV

### ISSUE THREAD

**Issue by etiennemontenegro** [a3lab/crocodile#7]
Créer un script qui tranfsorme le fichier .wav contenant les biodatas en CSV.

Le fichier csv que l'on utilise présentement n'a pas de label pour les données. Le nouveau script pourrait les ajouter. 

Lien pour fichier wav. : https://drive.google.com/file/d/1eG9sjIJ-F3DPJXC30MYUt_JeGarHqALA/view?usp=sharing

**Comment by sofian** [comment]
Closed by 0ed50af5525d4c46d25232286725534a3fb4e685.
